# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
#build_app(scheme: "FastlaneDemo", workspace: "FastlaneDemo.xcodeproj", include_bitcode: true)
#get_certificates( development: true, username:"tringappsdev@gmail.com")
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :beta do
   #get_certificates( development: true)        
   #get_provisioning_profile   
   increment_build_number(xcodeproj:"FastlaneDemo.xcodeproj")
   #build_app(scheme: "FastlaneDemo", export_method:"development")
   #hockey(api_token: "a17d38733470464bb3e72a15b30dcaa4")
  end


lane :CurrentVersion do
get_version_number(xcodeproj:"FastlaneDemo.xcodeproj")
end

end


lane :tests do
  run_tests(scheme: "FastlaneDemo")
end




